#! /usr/bin/env python3.6
import sys
import math

def log2(x):
    return math.log(x, 2)

NF = .0001

posts = ('noun', 'verb', 'inf', 'prep', 'phi')

post_nums = {posts[i] : i for i in range(len(posts))}

PHI = post_nums['phi']

nums_post = dict()

for k,v in post_nums.items():
    nums_post[v] = k

num_posts = len(post_nums.keys())

print(posts, post_nums, nums_post)

probs = dict()

args = sys.argv

# Read probabilities
with open(args[1], 'r') as f:
    for l in f:
        s = l.strip().split()
        x = s[0].lower()
        y = s[1].lower()
        p = float(s[2])
        if y in probs.keys():
            probs[y][x] = p
        else:
            probs[y] = {x : p}
print(probs)

def emission_prob(w, t):
    return probs[nums_post[t]].get(w, NF)

def transition_prob(t2, t1):
    return probs[nums_post[t1]].get(nums_post[t2], NF)

def make_viterbi(s):
    s = s.strip().split()
    s = list(map(lambda x: x.lower(), s))
    v = [[None for x in s] for i in range(num_posts)]
    for i in range(num_posts):
        v[i][0] = [(log2(emission_prob(s[0], i)) +
                    log2(transition_prob(i, PHI))), None]
    return v

from pprint import pprint

pprint(make_viterbi("bears fish"))
